
version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb configrs/configServer1:27017,configServer2:27017,configServer3:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 15000:27017
