
version: '3'

services:

  shard3server1:
    container_name: shard3server1
    image: mongo
    command: mongod --shardsvr --replSet shard3rs --port 27017 --dbpath /data/db
    ports:
      - 13000:27017
    volumes:
      - shard3server1:/data/db

  shard3server2:
    container_name: shard3server2
    image: mongo
    command: mongod --shardsvr --replSet shard3rs --port 27017 --dbpath /data/db
    ports:
      - 13001:27017
    volumes:
      - shard3server2:/data/db

  shard3server3:
    container_name: shard3server3
    image: mongo
    command: mongod --shardsvr --replSet shard3rs --port 27017 --dbpath /data/db
    ports:
      - 13002:27017
    volumes:
      - shard3server3:/data/db

volumes:
  shard3server1: {}
  shard3server2: {}
  shard3server3: {}


